# -*- mode: ruby -*-
# vi: set ft=ruby :
Vagrant.configure("2") do |config|
    config.ssh.insert_key = false
    config.vbguest.auto_update = true
	
  # create Configuration Management (osmgmt) node
    config.vm.define :osmgmt do |mgmt_config|
      mgmt_config.vm.box = "ubuntu/bionic64"
      mgmt_config.vm.hostname = "osmgmt"
      mgmt_config.vm.network :private_network, ip: "192.168.56.10"
      mgmt_config.vm.synced_folder "test-tenant/", "/home/vagrant/test-tenant", mount_options: ["dmode=775"]
      mgmt_config.vm.provider "virtualbox" do |vb|
        vb.name = "osmgmt"
        opts = ["modifyvm", :id, "--natdnshostresolver1", "on"]
        vb.customize opts
        vb.memory = "1024"
      end
      mgmt_config.vm.provision :shell, path: "bootstrap-osmgmt.sh"
    end
end