# -*- mode: ruby -*-
# vi: set ft=ruby :
Vagrant.configure("2") do |config|

  config.ssh.insert_key = false
  config.vbguest.auto_update = true

  # create Google Cloud Platform Management (mgmt) node
  config.vm.define :osmgmt do |osmgmt_config|
    osmgmt_config.vm.box = "ubuntu/bionic64"
    osmgmt_config.vm.hostname = "osmgmt"
    osmgmt_config.vm.network :private_network, ip: "192.168.56.10"
    osmgmt_config.vm.synced_folder "test-tenant/", "/home/vagrant/test-tenant", mount_options: ["dmode=775"]
    osmgmt_config.vm.provider "virtualbox" do |vb|
      vb.name = "osmgmt"
      opts = ["modifyvm", :id, "--natdnshostresolver1", "on"]
      vb.customize opts
      vb.memory = "1024"
    end
    osmgmt_config.vm.provision :shell, path: "bootstrap-mgmt.sh"
  end

end
